//!!!!!!!!!!!!!!!!!! GENERATED BY createEntityInterfaces.sh - DON'T CHANGE IT !!!!!!!!!!!!!!!!!!
import { ConfigType } from './model/config.model';

export interface AppCfg extends OrmIntEntity {
  configId: string;
  type: ConfigType;
  value: string;
}

export interface UserCfg extends OwnedByUserEntity {
  configId: string;
  type: ConfigType;
  value: string;
}

export interface OrmBigIntEntity {
  id: number;
}

export interface OrmBigIntTimestampEntity extends OrmTimestampEntity {
  id: number;
}

export interface OrmIntEntity {
  id: number;
}

export interface OrmIntTimestampEntity extends OrmTimestampEntity {
  id: number;
}

export interface OrmTimestampEntity {
  updated?: Date;
  created?: Date;
}

export interface OrmUuidEntity {
  id?: string;
}

export interface OrmUuidTimestampEntity extends OrmTimestampEntity {
  id?: string;
}

export interface OwnedByUserEntity extends OrmIntTimestampEntity {
  user: User;
}

export interface User extends OrmIntTimestampEntity {
  name: string;
  password: string;
  admin: boolean;
  user: boolean;
  active: boolean;
}

export interface Company {
  id: number;
  name: string;
  location: string;
  active?: boolean;
}

export interface Person extends OwnedByUserEntity {
  name: string;
  pin: string;
  active: boolean;
  workingFor: Company;
}
